const ActionTypes = {
	clearLevel: 'EXECUTE_CLEAR_LEVEL',
	compare: 'COMPARE_CARDS',
	decreaseMoves: 'DECREASE_MOVES',
	decreaseScore: 'DECREASE_SCORE',
	decreaseSeconds: 'DECREASE_SECONDS', //(countdown)
	end: 'END_GAME',
	fillPowerbars: 'FILL_POWER_BARS',
	increaseMoves: 'EXECUTE_EXTRA_MOVES',
	increaseScore: 'INCREASE_SCORE',
	increaseSeconds: 'EXECUTE_EXTRA_TIME',
	lose: 'LEVEL_LOSE',
	match: 'CARDS_MATCH',
	nextLevel: 'NEXT_LEVEL',
	prevLevel: 'PREV_LEVEL',
	resetMoves: 'RESET_MOVES',
	resetScore: 'RESET_SCORE',
	resetSeconds: 'RESET_SECONDS',
	respawn: 'RESPAWN_TILES',
	reveal_card: 'REVEAL_CARD',
	showBoard: 'EXECUTE_SHOW_BOARD',
	shuffle: 'SHUFFLE_BOARD',
	start: 'START_GAME',
	updateMessage: 'UPDATE_MESSAGE',
	usePowerup: 'USE_POWERUP',
	wildcard: 'EXECUTE_WILDCARD',
	win: 'LEVEL_WIN',
};

export default ActionTypes;